### ISSUE TITLE
Integrate with liquid-fire

### ISSUE THREAD

**Issue by tim-evans** [movableink/ember-pop-over#1]
I would like to do some sort of sniffing to see if liquid-fire is installed, then use `{{liquid-if}}` instead of `{{if}}`. This would make integration fairly seamless

**Comment by green-arrow** [comment]
Looks like this is implemented already. Is there more to this that hasn't yet been implemented?

**Comment by tim-evans** [comment]
Probably. I'd check to see how well it works. I haven't really tested this integration thoroughly.

**Comment by tim-evans** [comment]
This is done enough to be marked as complete 😄
