### ISSUE TITLE
Remove `nearest-child` and `nearest-parent` computeds.

### ISSUE THREAD

**Issue by pzuraq** [movableink/ember-pop-over#10]
Nearest child and nearest parent are orthogonal to the way Ember works. Unit tests will fail if they are used in components, as the container is not defined. There is likely a better pattern for passing references between components.

They are also not dependencies of `ember-pop-over` as it stands. I propose they be lifted into their own microlibrary, or scrapped completely and replaced with a pattern that is more inline with Ember overall.

Our current pattern is as follows:

```
{{#pop-over for="someId" on="click" as |popover|}}
  <button {{action "close" popover}}>Close</button>
{{/pop-over}}
```

It's not as clean, but it is more inline with Ember norms. I'd definitely welcome a better pattern.

**Comment by tim-evans** [comment]
Gone! 😄 

I'll add actions to expose close and open for this.
