### ISSUE TITLE
parseActivators never called in target.js `on` computed property

### ISSUE THREAD

**Issue by Boubalou** [movableink/ember-pop-over#12]
The following pop-over ala 'tooltip' was working great under Ember 1.12 and fail with the following error under Ember 2.1:

`Uncaught TypeError: activators.contains is not a function` in `target.js line 214`.

From my understanding, for some reason, the computed property `on` is never called to execute the method `parseActivators()` which is responsible of creating an Array with the passed string.

Therefore, when a popup is rendered, the activators is still a `string` instead of an `array`.

Since you might know this addon from the inside out, maybe you can quickly help me or have encountered this before.

Thanks!

Below is what is being used to render the tooltip:

``` js
// components/tooltip-popup/component.js

import Ember from 'ember';

export default Ember.Component.extend({
  idGenerator: Ember.inject.service('id-generator'),

  classNames: ['tooltipPopup'],

  tooltipText: '',

  uniqueId: function() {
    return this.get('idGenerator').generate();
  }.property()
});
```

``` hbs
<!-- components/tooltip-popup/template.hbs -->

<div class='tooltipPopup-element' id={{uniqueId}}>
  {{inline-svg 'question-mark.svg' class='tooltipPopup-element-icon'}}
</div>

{{#pop-over for=uniqueId on='hover' class='tooltipPopup-popupMenu'}}
  <div class="popup-menu-tooltip">{{tooltipText}}</div>
{{/pop-over}}

```

What it suppose to render:
![screen shot 2015-10-29 at 10 29 10](https://cloud.githubusercontent.com/assets/513491/10821278/f2659580-7e27-11e5-9c16-56ec0d551507.png)

**Comment by tim-evans** [comment]
Could you write a failing test for this?

**Comment by Boubalou** [comment]
Oh boy, not sure I follow you there. Our time is pretty limited, I'll see what I can do to expose the issue clearly.

**Comment by tim-evans** [comment]
Thanks!

**Comment by Boubalou** [comment]
Hey Tim, 

Just retried the integration of your lib and couldn't reproduce the issue above, which is a good thing. No idea what you may have fixed, but whatever, I'll give it another try in our app.
