### ISSUE TITLE
Dropdown disappears when set to "on=click"

### ISSUE THREAD

**Issue by green-arrow** [movableink/ember-pop-over#15]
I am in the process of migrating from ember-popup-menu to this library, since it ember-popup-menu doesn't seem to be maintained anymore. I have many uses where I'm using `pop-over on="click"`. In these cases, the dropdown appears on click, but as soon as the mouse moves out of the target, the dropdown disappears. Is there something else I need to do or is this a bug?

**Comment by tim-evans** [comment]
Probably a bug. I haven't worked on this too heavily recently, and it still needs work.

**Comment by green-arrow** [comment]
That's fair. I will look into this some more and see if I can figure out what's going on :)

**Comment by green-arrow** [comment]
I believe I found the root cause of this issue. Upon inspection, `activeTargets` is an array, but `areAnyTargetsActive` is flagged as false. An ember issue has already been logged about this:

https://github.com/emberjs/ember.js/issues/12380
