### ISSUE TITLE
Presence of flow.js at the root of `app`

### ISSUE THREAD

**Issue by Boubalou** [movableink/ember-pop-over#19]
Hi,

Am I doing a bad manipulation when doing `ember install ember-pop-over`, because I end up having the file `flow.js` at the root of my application (`app/flow.js`). This is quite unusual for an addon to add files like that, is it the desired behavior?

Thanks!

**Comment by tim-evans** [comment]
Yes, it's desired behavior. It's done to match how liquid-fire works

**Comment by Boubalou** [comment]
:+1:
