### ISSUE TITLE
Manually close popover

### ISSUE THREAD

**Issue by Gabiras12** [movableink/ember-pop-over#24]
is there a way to manually close the popover?

**Comment by tim-evans** [comment]
Calling `deactivate` on the component should close the popover https://github.com/tim-evans/ember-pop-over/blob/master/addon/components/pop-over.js#L209

**Comment by Gabiras12** [comment]
Ohh! Great, but how can I do this?

i've tryed call deactivate like a action but this will not work.
`{{#pop-over active=popoverActive flow="dropdown" for="navigation-links" on="click}}"`
  `ul.pop-over__collection{action 'deactivate'}`
   `link-to 'route'`
      `li.pop-over__item A name`
 `{{/pop-over}}`

Any ideas?

@tim-evans

**Comment by tim-evans** [comment]
Not sure at the moment- I haven't used the popover in a while. I think it may have to expose the dismiss action as a param.

**Comment by sarus** [comment]
I did this by extending PopOver and adding a property that I observe:

```
import PopOver from "ember-pop-over/components/pop-over";
import Ember from "ember";

var DropDown = PopOver.extend({
  shouldHideObserver: Ember.observer('shouldHide', function(){
    this.hide();
  })
});

export default DropDown;
```

Then use it like this:

```
{{#drop-down for="explore" shouldHide=hideExploreActionsDropDown}}
{{/drop-down}}
```

When you want to hide the drop down manually just toggle the `hideExploreActionsDropDown` property which is picked up by the drop down observer causing `this.hide()` to be called which will hide the drop-down.

Feel a bit hacky but has been working for me so far.

**Comment by renatocarvalho** [comment]
+1

**Comment by tim-evans** [comment]
You may now set the popover on a parent component using the action `ondidinsert`. This action will send the popover instance to the component.
