### ISSUE TITLE
(v0.3.0) Import Statement from README appears to be incorrect

### ISSUE THREAD

**Issue by sarus** [movableink/ember-pop-over#31]
I upgraded to `v0.3.0` from `0.1.31` and started getting this error:

```
app.js:15 Uncaught Error: Could not find module `ember-pop-over/components/pop-over` imported from `app/components/sort-drop-down-menu`
```

My import statement was:

```
import PopOver from "ember-pop-over/components/pop-over";
```

Changing the import statement to:

```
import PopOver from "ember-pop-over/components/pop-over/component";
```

appears to have fixed the issue.   I think the change is required due to this https://github.com/tim-evans/ember-pop-over/commit/eed90d5677e5f89e84518c7dd41c2f2e5e769665 commit.

Assuming I'm not doing something wrong it would be great if the README could be updated to help other folks in the future coming to this project (or updating to the latest). 

Thanks for a great addon!

**Comment by tim-evans** [comment]
Ahh, yes. I'll fix that :)
