### ISSUE TITLE
Popover placement with position: relative parents

### ISSUE THREAD

**Issue by jakemauer** [movableink/ember-pop-over#38]
Hey Tim,

I have an issue where I'm trying to use popovers with a button inside of an element chain that has `position: relative` set on it. 

When this blue header (highlighted in red) is set to `position: relative` the tooltip renders down at the bottom of the page.

![position relative](https://cloud.githubusercontent.com/assets/361568/22812161/fbcd4e64-eef7-11e6-9a02-07ed244f69c6.png)

Here's how the tooltip renders when the header is `position: static`:
![position static](https://cloud.githubusercontent.com/assets/361568/22812163/fe74809c-eef7-11e6-9a9e-6b630b46bb3e.png)

Am I doing something wrong or missing a configuration param? 

Thanks again for all your work.

**Comment by tim-evans** [comment]
Ahh, this is due to the popover being `position: fixed`; we can make the positioning take into account the position of it's parent container.

**Comment by jakemauer** [comment]
Thanks Tim,

I'm willing to do the legwork. I've started looking through the source but am confused as to where positioning assignment happens. Also I suppose I have to change the re-assignment of position based on scroll.

**Comment by jakemauer** [comment]
And by that I mean, disable changing the popover's "top" when scroll events happen.

**Comment by tim-evans** [comment]
Oh, *that*. It happens when a `retile` happens. https://github.com/tim-evans/ember-pop-over/blob/master/addon/components/pop-over/component.js#L250

**Comment by jakemauer** [comment]
Hey Tim,

I'm closing this as this was my fault. For some reason a month ago I added `position: absolute` to `.popover` in my app's popovers.scss. I even commented in my commit but wasn't specific enough as to why. Removing it seems to fix all of my issues (go figure).

Thanks for your responsiveness!

**Comment by tim-evans** [comment]
no problem! :)
