### ISSUE TITLE
Move `dom-ruler` from bower to npm 

### ISSUE THREAD

**Issue by pzuraq** [movableink/ember-pop-over#8]
Bring structure inline with this RFC: https://github.com/chadhietala/rfcs/blob/packager/active/0002-packager.md

**Comment by tim-evans** [comment]
I'm working on moving this to broccoli-module-alchemist currently, but don't particularly like the idea of having two things to handle this :/

**Comment by patrickjholloway** [comment]
@tim-evans could we reopen this? I am unable to generate sourcemaps for my builds after removing bower from my app. Here is a similar issue with discussion on another addon: https://github.com/ember-cli/ember-cli/issues/7332

`ENOENT: no such file or directory, open '/Users/patrickholloway/kinvey/console/tmp/source_map_concat-input_base_path-d49NO0e6.tmp/bower_components/dom-ruler/dist/dom-ruler.amd.js'`

**Comment by tim-evans** [comment]
Hi @patrickjholloway I'm not sure how this is an issue any longer, since ember-pop-over doesn't use bower anymore

**Comment by patrickjholloway** [comment]
You have a dependency “dom-ruler” that uses bower. So anyone using your addon and trying to stop using bower cannot generate sourcemaps.

**Comment by tim-evans** [comment]
`dom-ruler` defines a bower file [here](https://github.com/tim-evans/dom-ruler/blob/master/bower.json), but doesn't have any bower dependencies. It's npm tarball and bower tarballs are static JS that's imported in ember.
