### ISSUE TITLE
Tiling issues (screenshots included)

### ISSUE THREAD

**Issue by pzuraq** [movableink/ember-pop-over#9]
Our app's calendar currently has a bug where the first time it is opened, the popover is placed too far right, resulting in overflow:

![screenshot 2015-05-22 17 26 14](https://cloud.githubusercontent.com/assets/685518/7781659/0ceb0154-00a8-11e5-8cb3-dc449f708223.png)

![screenshot 2015-05-22 17 26 39](https://cloud.githubusercontent.com/assets/685518/7781661/120ca07a-00a8-11e5-84ac-b548591174bf.png)

May be a bug with dom-ruler.

**Comment by tim-evans** [comment]
Hmm... sounds about right. And that's a beautiful calendar :)

Getting the browser to measure the right thing is a bit tricky- it is likely a race condition / off by 1 problem the first time.

**Comment by pzuraq** [comment]
Thanks! Hoping to release it soon!

The calendar and the date buttons on the right are floated next to each other. I experimented, and if the popover container width is set then everything works, so I'm guessing that the dom flow for floated elements isn't finished by the time that dom-ruler tries to tile.

Currently I don't see a need for dynamically sized popovers with floated elements. Users can likely provide a set width for those types of popovers. Thoughts?

**Comment by tim-evans** [comment]
If you walk through the retiling where measurement happens, I think you'll be able to determine what's going on. But if you can provide a reduced test case, I'll definitely take a look at it and see if I can crack that nut.
